[package]
name = "gen-epub-book"
description = "Generate an ePub book from a simple plaintext descriptor"
repository = "https://github.com/nabijaczleweli/gen-epub-book.rs"
documentation = "https://rawcdn.githack.com/nabijaczleweli/gen-epub-book.rs/doc/gen_epub_book/index.html"
readme = "README.md"
keywords = ["generate", "ePub", "ebook", "e-book", "book"]
categories = ["encoding", "text-processing"]
license = "MIT"
# Remember to also update in appveyor.yml
version = "2.3.1"
# Remember to also update in gen-epub-book.md
authors = ["nabijaczleweli <nabijaczleweli@gmail.com>"]

[dependencies]
lazy_static = "1.1"
mime_guess = "1.8"
reqwest = "0.9"
chrono = "0.4"
regex = "1.0"
clap = "2.32"
url = "1.7"
zip = "0.4"

[dependencies.uuid]
version = "0.7"
features = ["v4"]


[[bin]]
name = "gen-epub-book"
test = false
doc = false
